#ifndef MODELMATRIXIDS_H
#define MODELMATRIXIDS_H

// Parts after LINK_DL_ need to be kept in sync with Link_ShimDisplayList
//
// The ordering of items should not change to ensure backwards compatibility.
//
// MUST BE KEPT IN SYNC WITH PlayerModelManagerDisplayListId IN playermodelmanager_api.h
//
// If a backwards-incompatible change is made to this list, the API version in
// playermodelmanager_api.h must be bumped.
typedef enum Link_DisplayList {
    LINK_DL_WAIST,
    LINK_DL_RTHIGH,
    LINK_DL_RSHIN,
    LINK_DL_RFOOT,
    LINK_DL_LTHIGH,
    LINK_DL_LSHIN,
    LINK_DL_LFOOT,
    LINK_DL_HEAD,
    LINK_DL_HAT,
    LINK_DL_COLLAR,
    LINK_DL_LSHOULDER,
    LINK_DL_LFOREARM,
    LINK_DL_LHAND,
    LINK_DL_RSHOULDER,
    LINK_DL_RFOREARM,
    LINK_DL_RHAND,
    LINK_DL_SHEATH_NONE,
    LINK_DL_TORSO,

    // Other hand DLs
    LINK_DL_OPT_LFIST,
    LINK_DL_OPT_LHAND_BOTTLE,
    LINK_DL_OPT_LHAND_GUITAR,
    LINK_DL_OPT_RFIST,

    // Swords:
    //      1: Kokiri Sword
    //      2: Razor Sword
    //      3: Master Sword / Gilded Sword
    //      4: Giant's Knife / Biggoron Sword / Fierce Deity's Sword
    //      5: Great Fairy Sword

    LINK_DL_SWORD1_SHEATH,
    LINK_DL_SWORD2_SHEATH,
    LINK_DL_SWORD3_SHEATH,
    LINK_DL_SWORD4_SHEATH,
    LINK_DL_SWORD5_SHEATH,
    LINK_DL_SWORD1_HILT,
    LINK_DL_SWORD2_HILT,
    LINK_DL_SWORD3_HILT,
    LINK_DL_SWORD4_HILT,
    LINK_DL_SWORD5_HILT,
    LINK_DL_SWORD1_BLADE,
    LINK_DL_SWORD2_BLADE,
    LINK_DL_SWORD3_BLADE,
    LINK_DL_SWORD4_BLADE,
    LINK_DL_SWORD4_BLADE_BROKEN,
    LINK_DL_SWORD4_BLADE_FRAGMENT,
    LINK_DL_SWORD5_BLADE,

    LINK_DL_SHIELD1,     // Deku Shield
    LINK_DL_SHIELD2,     // Hylian Shield / Hero's Shield
    LINK_DL_SHIELD3,     // Mirror Shield
    LINK_DL_SHIELD3_RAY, // Mirror Shield Projection

    // Items
    LINK_DL_BOTTLE_GLASS,
    LINK_DL_BOTTLE_CONTENTS,
    LINK_DL_OCARINA_FAIRY,
    LINK_DL_OCARINA_TIME,
    LINK_DL_DEKU_STICK,
    LINK_DL_BOW, // Also has a first person variant
    LINK_DL_BOW_STRING,
    LINK_DL_BOW_ARROW,
    LINK_DL_SLINGSHOT,
    LINK_DL_SLINGSHOT_STRING,
    LINK_DL_HOOKSHOT,
    LINK_DL_HOOKSHOT_CHAIN,
    LINK_DL_HOOKSHOT_HOOK,
    LINK_DL_HOOKSHOT_RETICLE,
    LINK_DL_FPS_HOOKSHOT,
    LINK_DL_BOOMERANG,        // Boomerang model while held in hand
    LINK_DL_BOOMERANG_FLYING, // Boomerang model after being thrown
    LINK_DL_HAMMER,

    // First Person
    LINK_DL_OPT_FPS_LFOREARM,
    LINK_DL_OPT_FPS_LHAND,
    LINK_DL_OPT_FPS_RFOREARM,
    LINK_DL_OPT_FPS_RHAND,

    // Masks
    LINK_DL_MASK_SKULL,
    LINK_DL_MASK_SPOOKY,
    LINK_DL_MASK_GERUDO,
    LINK_DL_MASK_TRUTH,
    LINK_DL_MASK_KAFEIS_MASK,
    LINK_DL_MASK_ALL_NIGHT,
    LINK_DL_MASK_BUNNY, // May look odd due to animation
    LINK_DL_MASK_KEATON,
    LINK_DL_MASK_GARO,
    LINK_DL_MASK_ROMANI,
    LINK_DL_MASK_CIRCUS_LEADER,
    LINK_DL_MASK_COUPLE,
    LINK_DL_MASK_POSTMAN,
    LINK_DL_MASK_GREAT_FAIRY, // May look odd due to animation
    LINK_DL_MASK_GIBDO,
    LINK_DL_MASK_DON_GERO,
    LINK_DL_MASK_KAMARO,
    LINK_DL_MASK_CAPTAIN,
    LINK_DL_MASK_STONE,
    LINK_DL_MASK_BREMEN,
    LINK_DL_MASK_BLAST,
    LINK_DL_MASK_BLAST_COOLING_DOWN,
    LINK_DL_MASK_SCENTS,
    LINK_DL_MASK_GIANT,
    LINK_DL_MASK_DEKU,
    LINK_DL_MASK_GORON,
    LINK_DL_MASK_ZORA,
    LINK_DL_MASK_FIERCE_DEITY,
    LINK_DL_MASK_DEKU_SCREAM,
    LINK_DL_MASK_GORON_SCREAM,
    LINK_DL_MASK_ZORA_SCREAM,
    LINK_DL_MASK_FIERCE_DEITY_SCREAM,

    // Elegy of Emptiness statues (use LINK_DL_ELEGY_OF_EMPTINESS_SHELL instead)
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL_HUMAN_UNUSED,
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL_DEKU_UNUSED,
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL_GORON_UNUSED,
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL_ZORA_UNUSED,

    // Strength Upgrades (OoT)
    LINK_DL_BRACELET_LFOREARM,
    LINK_DL_GAUNTLET_LFOREARM,
    LINK_DL_GAUNTLET_LHAND,
    LINK_DL_GAUNTLET_LFIST,
    LINK_DL_GAUNTLET_RFOREARM,
    LINK_DL_GAUNTLET_RHAND,
    LINK_DL_GAUNTLET_RFIST,

    // Boots (OoT)
    LINK_DL_BOOT_LIRON,
    LINK_DL_BOOT_RIRON,
    LINK_DL_BOOT_LHOVER,
    LINK_DL_BOOT_RHOVER,

    // Deku Instrument / Pipes
    LINK_DL_DEKU_GUARD,
    LINK_DL_PIPE_MOUTH,
    LINK_DL_PIPE_RIGHT,
    LINK_DL_PIPE_UP,
    LINK_DL_PIPE_DOWN,
    LINK_DL_PIPE_LEFT,
    LINK_DL_PIPE_A,

    // Deku Propellers
    LINK_DL_STEM_RIGHT,
    LINK_DL_STEM_LEFT,
    LINK_DL_PETAL_PARTICLE,
    LINK_DL_FLOWER_PROPELLER_CLOSED,
    LINK_DL_FLOWER_CENTER_CLOSED,
    LINK_DL_FLOWER_PROPELLER_OPEN,
    LINK_DL_FLOWER_CENTER_OPEN,

    // Deku Pad DLs
    LINK_DL_PAD_WOOD,
    LINK_DL_PAD_GRASS,
    LINK_DL_PAD_OPENING,

    // Goron Instrument / Drums
    LINK_DL_DRUM_STRAP,
    LINK_DL_DRUM_UP,
    LINK_DL_DRUM_LEFT,
    LINK_DL_DRUM_RIGHT,
    LINK_DL_DRUM_DOWN,
    LINK_DL_DRUM_A,

    // Goron shield animation skeleton DLs
    LINK_DL_BODY_SHIELD_HEAD,
    LINK_DL_BODY_SHIELD_BODY,
    LINK_DL_BODY_SHIELD_ARMS_AND_LEGS,

    // Goron Roll / Goron Magic DLs
    LINK_DL_CURLED,
    LINK_DL_SPIKES,
    LINK_DL_FIRE_INIT,
    LINK_DL_FIRE_ROLL,
    LINK_DL_FIRE_PUNCH,

    // Zora Fins
    LINK_DL_LFIN,
    LINK_DL_LFIN_SWIM,
    LINK_DL_LFIN_BOOMERANG,
    LINK_DL_RFIN,
    LINK_DL_RFIN_SWIM,
    LINK_DL_RFIN_BOOMERANG,
    LINK_DL_FIN_SHIELD,

    // Zora Magic
    LINK_DL_MAGIC_BARRIER,

    // Zora Instrument / Guitar
    LINK_DL_GUITAR,

    // Keep these shim names in sync with Link_ShimDisplayList

    // Hilt + Blade
    LINK_DL_SWORD1,
    LINK_DL_SWORD2,
    LINK_DL_SWORD3,
    LINK_DL_SWORD4,
    LINK_DL_SWORD4_BROKEN,
    LINK_DL_SWORD5,

    // Hilt + Back Matrix
    LINK_DL_SWORD1_HILT_BACK,
    LINK_DL_SWORD2_HILT_BACK,
    LINK_DL_SWORD3_HILT_BACK,
    LINK_DL_SWORD4_HILT_BACK,
    LINK_DL_SWORD5_HILT_BACK,

    // Hilt w/ Back Matrix + Sheath
    LINK_DL_SWORD1_SHEATHED,
    LINK_DL_SWORD2_SHEATHED,
    LINK_DL_SWORD3_SHEATHED,
    LINK_DL_SWORD4_SHEATHED,
    LINK_DL_SWORD5_SHEATHED,

    // Shield w/ Back Matrix
    LINK_DL_SHIELD1_BACK,
    LINK_DL_SHIELD2_BACK,
    LINK_DL_SHIELD3_BACK,

    // Sheath + Shield w/ Back Matrix
    LINK_DL_SWORD1_SHIELD1_SHEATH,
    LINK_DL_SWORD1_SHIELD2_SHEATH,
    LINK_DL_SWORD1_SHIELD3_SHEATH,
    LINK_DL_SWORD2_SHIELD1_SHEATH,
    LINK_DL_SWORD2_SHIELD2_SHEATH,
    LINK_DL_SWORD2_SHIELD3_SHEATH,
    LINK_DL_SWORD3_SHIELD1_SHEATH,
    LINK_DL_SWORD3_SHIELD2_SHEATH,
    LINK_DL_SWORD3_SHIELD3_SHEATH,
    LINK_DL_SWORD4_SHIELD1_SHEATH,
    LINK_DL_SWORD4_SHIELD2_SHEATH,
    LINK_DL_SWORD4_SHIELD3_SHEATH,
    LINK_DL_SWORD5_SHIELD1_SHEATH,
    LINK_DL_SWORD5_SHIELD2_SHEATH,
    LINK_DL_SWORD5_SHIELD3_SHEATH,

    // Sheath + Shield w/ Back Matrix + Hilt w/ Back Matrix
    LINK_DL_SWORD1_SHIELD1_SHEATHED,
    LINK_DL_SWORD1_SHIELD2_SHEATHED,
    LINK_DL_SWORD1_SHIELD3_SHEATHED,
    LINK_DL_SWORD2_SHIELD1_SHEATHED,
    LINK_DL_SWORD2_SHIELD2_SHEATHED,
    LINK_DL_SWORD2_SHIELD3_SHEATHED,
    LINK_DL_SWORD3_SHIELD1_SHEATHED,
    LINK_DL_SWORD3_SHIELD2_SHEATHED,
    LINK_DL_SWORD3_SHIELD3_SHEATHED,
    LINK_DL_SWORD4_SHIELD1_SHEATHED,
    LINK_DL_SWORD4_SHIELD2_SHEATHED,
    LINK_DL_SWORD4_SHIELD3_SHEATHED,
    LINK_DL_SWORD5_SHIELD1_SHEATHED,
    LINK_DL_SWORD5_SHIELD2_SHEATHED,
    LINK_DL_SWORD5_SHIELD3_SHEATHED,

    // Left Fist + Sword w/ Blade
    LINK_DL_LFIST_SWORD1,
    LINK_DL_LFIST_SWORD2,
    LINK_DL_LFIST_SWORD3,
    LINK_DL_LFIST_SWORD3_PEDESTAL_GRABBED,
    LINK_DL_LFIST_SWORD4,
    LINK_DL_LFIST_SWORD4_BROKEN,
    LINK_DL_LFIST_SWORD5,

    // Right Fist + Shield
    LINK_DL_RFIST_SHIELD1,
    LINK_DL_RFIST_SHIELD2,
    LINK_DL_RFIST_SHIELD3,

    // Reserved (OoT)
    LINK_DL_SHIELD1_ITEM,            // Burning Deku Shield
    LINK_DL_SWORD3_PEDESTAL,         // Master Sword rotated to be inside pedestal
    LINK_DL_SWORD3_PEDESTAL_GRABBED, // Master Sword rotated for grabbed from pedestal

    // Left Fist + Items
    LINK_DL_LFIST_HAMMER,
    LINK_DL_LFIST_BOOMERANG,

    // Right Fist + Items
    LINK_DL_RFIST_BOW,
    LINK_DL_RFIST_SLINGSHOT,
    LINK_DL_RFIST_HOOKSHOT,
    LINK_DL_RHAND_OCARINA_FAIRY,
    LINK_DL_RHAND_OCARINA_TIME,

    // First Person Right Hand + Items
    LINK_DL_FPS_RHAND_BOW,
    LINK_DL_FPS_RHAND_SLINGSHOT,
    LINK_DL_FPS_RHAND_HOOKSHOT,

    // Deku Link flower propellers
    LINK_DL_CENTER_FLOWER_PROPELLER_OPEN,
    LINK_DL_CENTER_FLOWER_PROPELLER_CLOSED,

    // First Person Bow
    LINK_DL_FPS_BOW,

    // First Person Slingshot
    LINK_DL_FPS_SLINGSHOT,

    // Fierce Deity Elegy of Emptiness Statue (use LINK_DL_ELEGY_OF_EMPTINESS_SHELL)
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL_FIERCE_DEITY_UNUSED,

    // Mirror Shield Projection Beam
    LINK_DL_SHIELD3_RAY_BEAM,

    // Longshot optional DLs
    LINK_DL_OPT_LONGSHOT,
    LINK_DL_OPT_LONGSHOT_CHAIN,
    LINK_DL_OPT_LONGSHOT_HOOK,
    LINK_DL_OPT_LONGSHOT_RETICLE,
    LINK_DL_OPT_FPS_LONGSHOT,

    // These hand models are optionally specified
    LINK_DL_OPT_LFIST_ITEM,
    LINK_DL_OPT_LFIST_SWORD,
    LINK_DL_OPT_LFIST_SWORD1,
    LINK_DL_OPT_LFIST_SWORD2,
    LINK_DL_OPT_LFIST_SWORD3,
    LINK_DL_OPT_LFIST_SWORD_TWO_HANDED,
    LINK_DL_OPT_LFIST_SWORD4,
    LINK_DL_OPT_LFIST_SWORD5,
    LINK_DL_OPT_LFIST_DEKU_STICK,
    LINK_DL_OPT_LFIST_HAMMER,
    LINK_DL_OPT_LFIST_BOOMERANG,

    LINK_DL_OPT_RHAND_OCARINA,
    LINK_DL_OPT_RHAND_OCARINA_FAIRY,
    LINK_DL_OPT_RHAND_OCARINA_TIME,

    LINK_DL_OPT_RFIST_ITEM,
    LINK_DL_OPT_RFIST_SHIELD,
    LINK_DL_OPT_RFIST_SHIELD1,
    LINK_DL_OPT_RFIST_SHIELD2,
    LINK_DL_OPT_RFIST_SHIELD3,
    LINK_DL_OPT_RFIST_SWORD_TWO_HANDED,
    LINK_DL_OPT_RFIST_SWORD4,
    LINK_DL_OPT_RFIST_SWORD5,
    LINK_DL_OPT_RFIST_DEKU_STICK,
    LINK_DL_OPT_RFIST_HAMMER,
    LINK_DL_OPT_RFIST_HOOKSHOT,
    LINK_DL_OPT_RFIST_LONGSHOT,
    LINK_DL_OPT_RFIST_BOW,
    LINK_DL_OPT_RFIST_SLINGSHOT,

    LINK_DL_OPT_FPS_LSHOULDER,
    LINK_DL_OPT_FPS_LSHOULDER_HOOKSHOT,
    LINK_DL_OPT_FPS_LSHOULDER_LONGSHOT,
    LINK_DL_OPT_FPS_LSHOULDER_BOW,
    LINK_DL_OPT_FPS_LSHOULDER_SLINGSHOT,

    LINK_DL_OPT_FPS_LFOREARM_HOOKSHOT,
    LINK_DL_OPT_FPS_LFOREARM_LONGSHOT,
    LINK_DL_OPT_FPS_LFOREARM_BOW,
    LINK_DL_OPT_FPS_LFOREARM_SLINGSHOT,

    LINK_DL_OPT_FPS_LHAND_HOOKSHOT,
    LINK_DL_OPT_FPS_LHAND_LONGSHOT,
    LINK_DL_OPT_FPS_LHAND_BOW,
    LINK_DL_OPT_FPS_LHAND_SLINGSHOT,

    LINK_DL_OPT_FPS_RSHOULDER,
    LINK_DL_OPT_FPS_RSHOULDER_HOOKSHOT,
    LINK_DL_OPT_FPS_RSHOULDER_LONGSHOT,
    LINK_DL_OPT_FPS_RSHOULDER_BOW,
    LINK_DL_OPT_FPS_RSHOULDER_SLINGSHOT,

    LINK_DL_OPT_FPS_RFOREARM_HOOKSHOT,
    LINK_DL_OPT_FPS_RFOREARM_LONGSHOT,
    LINK_DL_OPT_FPS_RFOREARM_BOW,
    LINK_DL_OPT_FPS_RFOREARM_SLINGSHOT,

    LINK_DL_OPT_FPS_RHAND_HOOKSHOT,
    LINK_DL_OPT_FPS_RHAND_LONGSHOT,
    LINK_DL_OPT_FPS_RHAND_BOW,
    LINK_DL_OPT_FPS_RHAND_SLINGSHOT,

    // Right hand holding longshot shim DLs
    LINK_DL_RFIST_LONGSHOT,
    LINK_DL_FPS_RHAND_LONGSHOT,

    // Bomb DLs
    LINK_DL_BOMB_BODY_2D,
    LINK_DL_BOMB_BODY_3D,
    LINK_DL_BOMB_CAP,

    // Powder Keg DLs (currently unused)
    // Reason: Models are stored in bomb overlay
    LINK_DL_POWDER_KEG_BODY,
    LINK_DL_POWDER_KEG_FUSE1,
    LINK_DL_POWDER_KEG_FUSE2,

    // Bombchu DL
    LINK_DL_BOMBCHU,

    // General elegy of emptiness DL
    LINK_DL_ELEGY_OF_EMPTINESS_SHELL,

    LINK_DL_MAX
} Link_DisplayList;

#define LINK_DL_LONGSHOT LINK_DL_OPT_LONGSHOT

#define LINK_DL_SWORD_KOKIRI_SHEATH LINK_DL_SWORD1_SHEATH
#define LINK_DL_SWORD_RAZOR_SHEATH LINK_DL_SWORD2_SHEATH
#define LINK_DL_SWORD_GILDED_SHEATH LINK_DL_SWORD3_SHEATH
#define LINK_DL_SWORD_MASTER_SHEATH LINK_DL_SWORD3_SHEATH

#define LINK_DL_SWORD_KOKIRI_HILT LINK_DL_SWORD1_HILT
#define LINK_DL_SWORD_RAZOR_HILT LINK_DL_SWORD2_HILT
#define LINK_DL_SWORD_GILDED_HILT LINK_DL_SWORD3_HILT
#define LINK_DL_SWORD_MASTER_HILT LINK_DL_SWORD3_HILT

#define LINK_DL_SWORD_KOKIRI_BLADE LINK_DL_SWORD1_BLADE
#define LINK_DL_SWORD_RAZOR_BLADE LINK_DL_SWORD2_BLADE
#define LINK_DL_SWORD_GILDED_BLADE LINK_DL_SWORD3_BLADE
#define LINK_DL_SWORD_FIERCE_DEITY_HILT LINK_DL_SWORD4_HILT
#define LINK_DL_SWORD_FIERCE_DEITY_BLADE LINK_DL_SWORD4_BLADE
#define LINK_DL_SWORD_BIGGORON_HILT LINK_DL_SWORD4_HILT
#define LINK_DL_SWORD_BIGGORON_BLADE LINK_DL_SWORD4_BLADE
#define LINK_DL_SWORD_GREAT_FAIRY_HILT LINK_DL_SWORD5_HILT
#define LINK_DL_SWORD_GREAT_FAIRY_BLADE LINK_DL_SWORD5_BLADE

#define LINK_DL_SHIELD_HERO LINK_DL_SHIELD2
#define LINK_DL_SHIELD_HYLIAN LINK_DL_SHIELD2
#define LINK_DL_SHIELD_MIRROR LINK_DL_SHIELD3

#define LINK_DL_SHIELD_MIRROR_RAY LINK_DL_SHIELD3_RAY
#define LINK_DL_SHIELD_MIRROR_RAY_BEAM LINK_DL_SHIELD3_RAY_BEAM

#define LINK_DL_SWORD_KOKIRI_SHEATHED LINK_DL_SWORD1_SHEATHED
#define LINK_DL_SWORD_RAZOR_SHEATHED LINK_DL_SWORD2_SHEATHED
#define LINK_DL_SWORD_GILDED_SHEATHED LINK_DL_SWORD3_SHEATHED
#define LINK_DL_SWORD_MASTER_SHEATHED LINK_DL_SWORD3_SHEATHED

#define LINK_DL_SHIELD_HERO_BACK LINK_DL_SHIELD2_BACK
#define LINK_DL_SHIELD_HYLIAN_BACK LINK_DL_SHIELD2_BACK
#define LINK_DL_SHIELD_MIRROR_BACK LINK_DL_SHIELD3_BACK

#define LINK_DL_SWORD_KOKIRI_SHIELD_HERO_BACK LINK_DL_SWORD1_SHIELD2_SHEATHED
#define LINK_DL_SWORD_KOKIRI_SHIELD_HYLIAN_BACK LINK_DL_SWORD1_SHIELD2_SHEATHED
#define LINK_DL_SWORD_KOKIRI_SHIELD_MIRROR_BACK LINK_DL_SWORD1_SHIELD3_SHEATHED

#define LINK_DL_SWORD_RAZOR_SHIELD_HERO_BACK LINK_DL_SWORD2_SHIELD2_SHEATHED
#define LINK_DL_SWORD_RAZOR_SHIELD_HYLIAN_BACK LINK_DL_SWORD2_SHIELD2_SHEATHED
#define LINK_DL_SWORD_RAZOR_SHIELD_MIRROR_BACK LINK_DL_SWORD2_SHIELD3_SHEATHED

#define LINK_DL_SWORD_GILDED_SHIELD_HERO_BACK LINK_DL_SWORD3_SHIELD2_SHEATHED
#define LINK_DL_SWORD_GILDED_SHIELD_HYLIAN_BACK LINK_DL_SWORD3_SHIELD2_SHEATHED
#define LINK_DL_SWORD_GILDED_SHIELD_MIRROR_BACK LINK_DL_SWORD3_SHIELD3_SHEATHED

#define LINK_DL_LFIST_SWORD_KOKIRI LINK_DL_LFIST_SWORD1
#define LINK_DL_LFIST_SWORD_RAZOR LINK_DL_LFIST_SWORD2
#define LINK_DL_LFIST_SWORD_GILDED LINK_DL_LFIST_SWORD3
#define LINK_DL_LFIST_SWORD_MASTER LINK_DL_LFIST_SWORD3
#define LINK_DL_LFIST_SWORD_FIERCE_DEITY LINK_DL_LFIST_SWORD4
#define LINK_DL_LFIST_SWORD_BIGGORON LINK_DL_LFIST_SWORD4
#define LINK_DL_LFIST_SWORD_GREAT_FAIRY LINK_DL_LFIST_SWORD5

#define LINK_DL_RFIST_SHIELD_HERO LINK_DL_RFIST_SHIELD2
#define LINK_DL_RFIST_SHIELD_HYLIAN LINK_DL_RFIST_SHIELD2
#define LINK_DL_RFIST_SHIELD_MIRROR LINK_DL_RFIST_SHIELD3

#define LINK_DL_OPT_FPS_BOW LINK_DL_FPS_BOW
#define LINK_DL_OPT_FPS_SLINGSHOT LINK_DL_FPS_SLINGSHOT
#define LINK_DL_OPT_FPS_HOOKSHOT LINK_DL_FPS_HOOKSHOT

#define LINK_EQUIP_MATRIX_SWORD_KOKIRI_BACK LINK_EQUIP_MATRIX_SWORD1_BACK
#define LINK_EQUIP_MATRIX_SWORD_RAZOR_BACK LINK_EQUIP_MATRIX_SWORD2_BACK
#define LINK_EQUIP_MATRIX_SWORD_GILDED_BACK LINK_EQUIP_MATRIX_SWORD3_BACK
#define LINK_EQUIP_MATRIX_SWORD_MASTER_BACK LINK_EQUIP_MATRIX_SWORD3_BACK
#define LINK_EQUIP_MATRIX_SHIELD_HERO_BACK LINK_EQUIP_MATRIX_SHIELD2_BACK
#define LINK_EQUIP_MATRIX_SHIELD_HYLIAN_BACK LINK_EQUIP_MATRIX_SHIELD2_BACK
#define LINK_EQUIP_MATRIX_SHIELD_MIRROR_BACK LINK_EQUIP_MATRIX_SHIELD3_BACK

// Parts after LINK_SHIMDL_ need to be kept in sync with Link_DisplayList
typedef enum Link_ShimDisplayList {
    // Hilt + Blade
    LINK_SHIMDL_SWORD1,
    LINK_SHIMDL_SWORD2,
    LINK_SHIMDL_SWORD3,
    LINK_SHIMDL_SWORD4,
    LINK_SHIMDL_SWORD4_BROKEN,
    LINK_SHIMDL_SWORD5,

    // Hilt + Back Matrix
    LINK_SHIMDL_SWORD1_HILT_BACK,
    LINK_SHIMDL_SWORD2_HILT_BACK,
    LINK_SHIMDL_SWORD3_HILT_BACK,
    LINK_SHIMDL_SWORD4_HILT_BACK,
    LINK_SHIMDL_SWORD5_HILT_BACK,

    // Hilt w/ Back Matrix + Sheath
    LINK_SHIMDL_SWORD1_SHEATHED,
    LINK_SHIMDL_SWORD2_SHEATHED,
    LINK_SHIMDL_SWORD3_SHEATHED,
    LINK_SHIMDL_SWORD4_SHEATHED,
    LINK_SHIMDL_SWORD5_SHEATHED,

    // Shield w/ Back Matrix
    LINK_SHIMDL_SHIELD1_BACK,
    LINK_SHIMDL_SHIELD2_BACK,
    LINK_SHIMDL_SHIELD3_BACK,

    // Sheath + Shield w/ Back Matrix
    LINK_SHIMDL_SWORD1_SHIELD1_SHEATH,
    LINK_SHIMDL_SWORD1_SHIELD2_SHEATH,
    LINK_SHIMDL_SWORD1_SHIELD3_SHEATH,
    LINK_SHIMDL_SWORD2_SHIELD1_SHEATH,
    LINK_SHIMDL_SWORD2_SHIELD2_SHEATH,
    LINK_SHIMDL_SWORD2_SHIELD3_SHEATH,
    LINK_SHIMDL_SWORD3_SHIELD1_SHEATH,
    LINK_SHIMDL_SWORD3_SHIELD2_SHEATH,
    LINK_SHIMDL_SWORD3_SHIELD3_SHEATH,
    LINK_SHIMDL_SWORD4_SHIELD1_SHEATH,
    LINK_SHIMDL_SWORD4_SHIELD2_SHEATH,
    LINK_SHIMDL_SWORD4_SHIELD3_SHEATH,
    LINK_SHIMDL_SWORD5_SHIELD1_SHEATH,
    LINK_SHIMDL_SWORD5_SHIELD2_SHEATH,
    LINK_SHIMDL_SWORD5_SHIELD3_SHEATH,

    // Sheath + Shield w/ Back Matrix + Hilt w/ Back Matrix
    LINK_SHIMDL_SWORD1_SHIELD1_SHEATHED,
    LINK_SHIMDL_SWORD1_SHIELD2_SHEATHED,
    LINK_SHIMDL_SWORD1_SHIELD3_SHEATHED,
    LINK_SHIMDL_SWORD2_SHIELD1_SHEATHED,
    LINK_SHIMDL_SWORD2_SHIELD2_SHEATHED,
    LINK_SHIMDL_SWORD2_SHIELD3_SHEATHED,
    LINK_SHIMDL_SWORD3_SHIELD1_SHEATHED,
    LINK_SHIMDL_SWORD3_SHIELD2_SHEATHED,
    LINK_SHIMDL_SWORD3_SHIELD3_SHEATHED,
    LINK_SHIMDL_SWORD4_SHIELD1_SHEATHED,
    LINK_SHIMDL_SWORD4_SHIELD2_SHEATHED,
    LINK_SHIMDL_SWORD4_SHIELD3_SHEATHED,
    LINK_SHIMDL_SWORD5_SHIELD1_SHEATHED,
    LINK_SHIMDL_SWORD5_SHIELD2_SHEATHED,
    LINK_SHIMDL_SWORD5_SHIELD3_SHEATHED,

    // Left Fist + Sword w/ Blade
    LINK_SHIMDL_LFIST_SWORD1,
    LINK_SHIMDL_LFIST_SWORD2,
    LINK_SHIMDL_LFIST_SWORD3,
    LINK_SHIMDL_LFIST_SWORD3_PEDESTAL_GRABBED,
    LINK_SHIMDL_LFIST_SWORD4,
    LINK_SHIMDL_LFIST_SWORD4_BROKEN,
    LINK_SHIMDL_LFIST_SWORD5,

    // Right Fist + Shield
    LINK_SHIMDL_RFIST_SHIELD1,
    LINK_SHIMDL_RFIST_SHIELD2,
    LINK_SHIMDL_RFIST_SHIELD3,

    // Hands + Items
    LINK_SHIMDL_LFIST_HAMMER,
    LINK_SHIMDL_LFIST_BOOMERANG,
    LINK_SHIMDL_RFIST_BOW,
    LINK_SHIMDL_RFIST_SLINGSHOT,
    LINK_SHIMDL_RFIST_HOOKSHOT,
    LINK_SHIMDL_RFIST_LONGSHOT,
    LINK_SHIMDL_RHAND_OCARINA_FAIRY,
    LINK_SHIMDL_RHAND_OCARINA_TIME,

    // First Person Items
    LINK_SHIMDL_FPS_RHAND_BOW,
    LINK_SHIMDL_FPS_RHAND_SLINGSHOT,
    LINK_SHIMDL_FPS_RHAND_HOOKSHOT,
    LINK_SHIMDL_FPS_RHAND_LONGSHOT,

    // Reserved (OoT)
    LINK_SHIMDL_SHIELD1_ITEM,
    LINK_SHIMDL_SWORD3_PEDESTAL,
    LINK_SHIMDL_SWORD3_PEDESTAL_GRABBED,

    // Deku Link Propellers
    LINK_SHIMDL_CENTER_FLOWER_PROPELLER_OPEN,
    LINK_SHIMDL_CENTER_FLOWER_PROPELLER_CLOSED,

    // # of shim DLs
    LINK_SHIMDL_MAX,
} Link_ShimDisplayList;

// Parts after LINK_EQUIP need to be kept in sync with Link_ShimDisplayList
//
// MUST BE KEPT IN SYNC WITH PlayerModelManagerMatrixId IN playermodelmanager_api.h
typedef enum Link_EquipmentMatrix {
    LINK_EQUIP_MATRIX_SWORD1_BACK,
    LINK_EQUIP_MATRIX_SWORD2_BACK,
    LINK_EQUIP_MATRIX_SWORD3_BACK,
    LINK_EQUIP_MATRIX_SWORD4_BACK,
    LINK_EQUIP_MATRIX_SWORD5_BACK,
    LINK_EQUIP_MATRIX_SHIELD1_BACK,
    LINK_EQUIP_MATRIX_SHIELD2_BACK,
    LINK_EQUIP_MATRIX_SHIELD3_BACK,
    LINK_EQUIP_MATRIX_SHIELD1_ITEM,
    LINK_EQUIP_MATRIX_SWORD3_PEDESTAL,
    LINK_EQUIP_MATRIX_SWORD3_PEDESTAL_GRABBED,
    LINK_EQUIP_MATRIX_MASKS,
    LINK_EQUIP_MATRIX_ARROW_DRAWN,
    LINK_EQUIP_MATRIX_HOOKSHOT_CHAIN_AND_HOOK,
    LINK_EQUIP_MATRIX_MAX,
} Link_EquipmentMatrix;

typedef enum LinkShieldingLimb {
    /* 0x00 */ LINK_BODY_SHIELD_LIMB_NONE,
    /* 0x01 */ LINK_BODY_SHIELD_LIMB_ROOT,
    /* 0x02 */ LINK_BODY_SHIELD_LIMB_BODY,
    /* 0x03 */ LINK_BODY_SHIELD_LIMB_HEAD,
    /* 0x04 */ LINK_BODY_SHIELD_LIMB_ARMS_AND_LEGS,
    /* 0x05 */ LINK_BODY_SHIELD_LIMB_MAX
} LinkShieldingLimb;

typedef unsigned long FormProxyId;

extern FormProxyId const *const gFormProxyIdFierceDeity;
extern FormProxyId const *const gFormProxyIdGoron;
extern FormProxyId const *const gFormProxyIdZora;
extern FormProxyId const *const gFormProxyIdDeku;
extern FormProxyId const *const gFormProxyIdHuman;

#define FORM_PROXY_ID_NONE ((FormProxyId)0)
#define FORM_PROXY_ID_FIERCE_DEITY (*gFormProxyIdFierceDeity)
#define FORM_PROXY_ID_GORON (*gFormProxyIdGoron)
#define FORM_PROXY_ID_ZORA (*gFormProxyIdZora)
#define FORM_PROXY_ID_DEKU (*gFormProxyIdDeku)
#define FORM_PROXY_ID_HUMAN (*gFormProxyIdHuman)

#endif
